import NavBar from '@/components/UserInfo'
import './globals.css'
import { Outfit } from 'next/font/google'

const outfit = Outfit( {
  // weight: ['400', '500', '600', '700', '800'],
  display: 'swap',
  subsets: ['latin']
})


export const metadata = {
  title: 'CoinMarket',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className='font-outfit'>
       
        {children}
        </body>
    </html>
  )
}
